if: (branch = master) OR (type = pull_request) OR (tag =~ /^\d+\.\d+\.\d+(-.*)?$/)

stages:
  - name: validate tests
  - name: test
  - name: publish docs
    if: tag =~ /^\d+\.\d+\.\d+(-.*)?$/

os: osx
language: swift
xcode_project: Xcode/AuthScope.xcodeproj
xcode_scheme: AuthScope

jobs:
  include:
    - stage: validate tests
      name: Validate SwiftPM generated linux test files
      osx_image: xcode10.2
      script: swift test --generate-linuxmain && git diff --exit-code

    - &linux
      stage: test
      name: SwiftPM Release Linux
      os: linux
      dist: bionic
      language: generic
      env:
        - SWIFT_PLATFORM="ubuntu18.04"
        - SWIFT_BRANCH="swift-5.0.2-release"
        - SWIFT_VERSION="swift-5.0.2-RELEASE"
      install: eval "$(curl -sL 'https://bitbucket.org/!api/2.0/snippets/sersoftgmbh/7AgnAp/be8f565b217c9631f2a17ed6fad96486f881297e/files/install_swift_linux.sh')"
      script: swift test --parallel

    - <<: *linux
      name: SwiftPM Beta Linux
      env:
        - SWIFT_BRANCH="swift-5.1-branch"
        - SWIFT_VERSION="swift-5.1-DEVELOPMENT-SNAPSHOT-2019-07-25-a"

    - &macOS
      stage: test
      name: SwiftPM Release macOS
      osx_image: xcode10.2
      script: swift test --parallel

    - <<: *macOS
      name: SwiftPM Beta macOS
      osx_image: xcode11

    - &xcode
      stage: test
      name: macOS Swift Release
      osx_image: xcode10.2
      xcode_destination: platform=macOS
      after_success: bash <(curl -s https://codecov.io/bash) -J "AuthScope"

    - <<: *xcode
      name: macOS Swift Beta
      osx_image: xcode11
      xcode_destination: platform=macOS

    - <<: *xcode
      name: iOS Swift Release
      xcode_destination: platform=iOS Simulator,OS=latest,name=iPhone Xs Max

    - <<: *xcode
      name: iOS Swift Beta
      osx_image: xcode11
      xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone Xs Max

    - <<: *xcode
      name: tvOS Swift Release
      xcode_destination: platform=tvOS Simulator,OS=latest,name=Apple TV 4K

    - <<: *xcode
      name: tvOS Swift Beta
      osx_image: xcode11
      xcode_destination: platform=tvOS Simulator,OS=13.0,name=Apple TV 4K

    - <<: *xcode
      name: watchOS Swift Release
      script: |
        set -o pipefail
        xcodebuild -project "${TRAVIS_XCODE_PROJECT}" -scheme "${TRAVIS_XCODE_SCHEME}" \
          -destination 'platform=watchOS Simulator,OS=latest,name=Apple Watch Series 4 - 44mm' \
          build | xcpretty
      after_success: false

    - <<: *xcode
      name: watchOS Swift Beta
      osx_image: xcode11
      script: |
        set -o pipefail
        xcodebuild -project "${TRAVIS_XCODE_PROJECT}" -scheme "${TRAVIS_XCODE_SCHEME}" \
          -destination 'platform=watchOS Simulator,OS=6.0,name=Apple Watch Series 4 - 44mm' \
          build | xcpretty
      after_success: false

    - stage: publish docs
      name: Generate and publish documentation
      osx_image: xcode10.2
      install: gem install jazzy
      script: jazzy --module-version $TRAVIS_TAG
      deploy:
        provider: pages
        github-token: $GITHUB_DOCS_TOKEN
        skip-cleanup: true
        local-dir: docs
        target_branch: gh-pages
        on:
          tags: true